INSERT INTO Shoe (product_name, size, price) VALUES
                                                ('Nike Air Max', 10, 100),
                                                ('Adidas Ultraboost', 9, 120),
                                                ('Puma RS-X', 11, 80),
                                                ('Reebok Classic', 8, 70),
                                                ('New Balance 574', 9, 90),
                                                ('Vans Old Skool', 8, 60),
                                                ('Converse Chuck Taylor', 9, 50),
                                                ('Skechers Go Walk', 10, 75),
                                                ('Under Armour HOVR', 11, 110),
                                                ('Brooks Ghost', 10, 130),
                                                ('Asics Gel-Kayano', 9, 140),
                                                ('Salomon Speedcross', 10, 150),
                                                ('Mizuno Wave Rider', 8, 95),
                                                ('Hoka One One Clifton', 9, 125),
                                                ('Merrell Moab', 10, 85),
                                                ('Timberland Chukka', 11, 110),
                                                ('Columbia Redmond', 9, 75),
                                                ('Keen Targhee', 10, 100),
                                                ('Birkenstock Arizona', 8, 80),
                                                ('Dr. Martens 1460', 9, 130);
